#pragma once

/// @file PayloadHal.h
/// @brief Master aggregate header for the Payload Hardware Abstraction Layer (PayloadHal).

#include "CameraStreamBinder.h"
#include "DemRayCaster.h"
#include "GeoLockController.h"
#include "GeoreferenceUtils.h"
#include "GridDemProvider.h"
#include "ICameraPayload.h"
#include "IDemProvider.h"
#include "IDevice.h"
#include "ILaserIlluminator.h"
#include "ILaserRangeFinder.h"
#include "IPanTiltUnit.h"
#include "IPayload.h"
#include "IPtzPresetManager.h"
#include "LocalPresetManager.h"
#include "TourEngine.h"
#include "TacticalSearchEngine.h"
#include "SensorParallaxCompensator.h"
#include "PlatformLeverArmCompensator.h"
#include "PayloadAutoTrackerBridge.h"
#include "PayloadFactory.h"
#include "PayloadKlvGenerator.h"
#include "PayloadTypes.h"
#include "VideoStreamTypes.h"
#include "adapters/OnvifPayloadAdapter.h"
#include "adapters/PelcoDFujinonPayloadAdapter.h"
#include "adapters/PelcoDPtzAdapter.h"
#include "adapters/PelcoDViscaCompositePayload.h"
#include "adapters/ViscaSonyAdapter.h"
#include "sim/SimulatedPayload.h"
