add_subdirectory(Transport)
add_subdirectory(Math)
add_subdirectory(PelcoDCore)
add_subdirectory(ViscaCore)
add_subdirectory(ViscaSony)
if(BUILD_TESTING)
    add_subdirectory(TestSupport)
endif()
add_subdirectory(Tracking)
add_subdirectory(Klv)
add_subdirectory(Mapping)
add_subdirectory(PelcoDFujinon)
add_subdirectory(PelcoDSim)
add_subdirectory(PayloadHal)

if(PELCOD_ENABLE_ONVIF)
    add_subdirectory(Onvif)
endif()

add_subdirectory(PelcoDQt)
add_subdirectory(MappingQt)

if(PELCOD_ENABLE_VIDEO)
    add_subdirectory(Video)
    if(PELCOD_ENABLE_FILTERS AND OpenCV_FOUND)
        add_subdirectory(VideoFilters)
    endif()
endif()
